In [1]:
import tensorflow as tf

In [2]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [3]:
t

<tf.Tensor: id=0, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
t.shape

TensorShape([2, 3])

In [5]:
t.dtype

tf.float32

In [8]:
t[:, 1:2]  # Intervals are [a,b)

<tf.Tensor: id=12, shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [9]:
t+10

<tf.Tensor: id=14, shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [10]:
tf.square(t)

<tf.Tensor: id=15, shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [12]:
tf.transpose(t)

<tf.Tensor: id=17, shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [14]:
t @ tf.transpose(t) # Matrix product

<tf.Tensor: id=23, shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [15]:
t+t

<tf.Tensor: id=24, shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [16]:
t+tf.constant(1)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: add/

In [17]:
tf.constant(1)

<tf.Tensor: id=26, shape=(), dtype=int32, numpy=1>

In [18]:
t

<tf.Tensor: id=0, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [25]:
t+tf.constant([1.0])

<tf.Tensor: id=35, shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [21]:
tf.constant(1.0)

<tf.Tensor: id=29, shape=(), dtype=float32, numpy=1.0>

In [26]:
tf.constant([1,2])

<tf.Tensor: id=36, shape=(2,), dtype=int32, numpy=array([1, 2])>

In [27]:
t

<tf.Tensor: id=0, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [30]:
tf.constant(t.numpy())

<tf.Tensor: id=37, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [32]:
tf.constant(['Coffee', 'káva'])

<tf.Tensor: id=39, shape=(2,), dtype=string, numpy=array([b'Coffee', b'k\xc3\xa1va'], dtype=object)>

In [34]:
tf.constant("Hello world!")

<tf.Tensor: id=40, shape=(), dtype=string, numpy=b'Hello world!'>

### Variable tensors

In [35]:
v = tf.Variable([[1.,2., 3.], [4.,5.,6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [36]:
v.value()

<tf.Tensor: id=50, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [37]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [38]:
v[0,1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [39]:
v[0,1] = 42

TypeError: 'ResourceVariable' object does not support item assignment